variable "instance_count" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnets" {}
variable "volume_size" {}
variable "key_name" {}
variable "key_path" {}
variable "userdata_path" {}
variable "db_endpoint" {}
variable "dbuser" {}
variable "dbpass" {}
variable "dbname" {}